a=imread('coin.png');
imshow(a)
b=imread('cat.jpg');
imshow(b)
c=imread('pawan.jpg');
imshow(c)
d=rgb2gray(c);
imshow(d)
e=imresize(d,[300,300]);
f=imresize(b,[300,300]);
h=rgb2gray(f);
g=e./h;
imshow(g);
subplot(2,2,1);
imshow(g);
title('division')
imshow(e+h);
title('addition')
x=e-h;
imshow(x);
subplot(2,3,2);
title('subraction')
w=e.*h;
imshow(w);
subplot(2,3,3);
title('multiplication')
y=e./h;
imshow(y);
subplot(2,3,4);
title('division')
k=e-h;
imshow(k);
subplot(2,3,1);
title('subraction')
aa=imshow(e)
subplot(2,3,5);
title('first picture')

